Feature/create client app part with offices
EugeneTryfanau/Clinic pull request #7
Opened 2024-03-18 13:49 UTC by EugeneTryfanau

finally everything what i wanted to do at the moment on client side is working

2024-03-18 14:27 UTC, Finka95 commented on client/clinic-react-client/src/components/offices/ActionPages/CreateWindow.tsx
> +    const [phone, setPhone] = useState('');
You can use single useState for the all 3 states.
{
address,
phone,
active
}

2024-03-18 14:27 UTC, Finka95 commented on client/clinic-react-client/src/components/offices/ActionPages/CreateWindow.tsx
> +        setActive('1');
And you can easy set this values here with 1 'set' call

2024-03-18 14:31 UTC, Finka95 requested changes

2024-03-18 14:31 UTC, Finka95 commented on client/clinic-react-client/src/configs/axiosConfig.ts
> +    baseURL: 'https://localhost:7056/api',
move this url to the env file

2024-03-19 07:34 UTC, Finka95 approved these changes

2024-03-19 08:40 UTC, Genresal approved these changes

2024-03-19 08:48 UTC, merged